# Generated by Django 5.2 on 2025-05-05 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Location Name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worn_at', models.DateTimeField(auto_now_add=True, verbose_name='Date worn')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Worn',
                'verbose_name_plural': 'Worn',
                'ordering': ['-worn_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Collection Name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.brand', verbose_name='Brand id')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Polish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Polish Name')),
                ('product_url', models.URLField(blank=True, null=True, verbose_name='Product URL')),
                ('check_url_at', models.DateTimeField(blank=True, null=True, verbose_name='Last checked URL at')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available online')),
                ('shade', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('grey', 'Grey'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow')], default='pink', max_length=20, verbose_name='Colour/Shade')),
                ('polish_type', models.CharField(choices=[('TC', 'Top Coat'), ('BC', 'Base Coat'), ('NP', 'Nail Polish'), ('US', 'Unicorn Skin'), ('TO', 'Nail Polish Topper')], default='NP', max_length=2, verbose_name='Polish Type')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.brand', verbose_name='Brand')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.collection', verbose_name='Collection name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Polish',
                'verbose_name_plural': 'Polishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WornLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Layer Order')),
                ('layer_type', models.CharField(choices=[('TC', 'Top Coat'), ('BC', 'Base Coat'), ('NP', 'Nail Polish'), ('US', 'Unicorn Skin'), ('TO', 'Nail Polish Topper')], default='BC', max_length=2, verbose_name='Layer Type')),
                ('polish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.polish', verbose_name='Polish Used')),
                ('worn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.worn')),
            ],
            options={
                'verbose_name': 'Worn Layers',
                'verbose_name_plural': 'Worn Layers',
                'ordering': ['worn', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WornPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_type', models.CharField(help_text="Example: 'flash on', 'macro', 'sunlight'. Try to reuse existing labels.", max_length=50, verbose_name='Photo Type')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Photo')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('worn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracker.worn', verbose_name='Worn')),
            ],
            options={
                'verbose_name': 'Worn Photo',
                'verbose_name_plural': 'Worn Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='polish',
            constraint=models.UniqueConstraint(fields=('brand', 'location', 'name'), name='unique_brand_location_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='wornlayers',
            constraint=models.UniqueConstraint(fields=('worn', 'order'), name='unique_worn_order'),
        ),
    ]
